### ISSUE TITLE
So how exactly this thing came to exist?

### ISSUE THREAD

**Issue by pieckenst** [Kaktushose/pascord#1]
Didn't expect anyone to make a discord bot lib for Pascal out of all the languages 
 So how exactly this thing came to exist?

**Comment by Kaktushose** [comment]
Back in the days at school I was forced to learn Pascal during cs classes. And it was that time where everyone was into discord bots since it was quite a new thing, so some friends and I, we were memeing about making a wrapper for Pascal. So yeah this is how it started, but tbh I have no idea if I will ever finish or actually start this project.

**Comment by pieckenst** [comment]
Yeah understandable tbh 
How working is this thing overall

**Comment by Kaktushose** [comment]
it's not. 
So far I have set up workflows for documentation and ci. I have also written a shitty logger class and a even shittier http class that can only send a test message to my testing server
